#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H
/*intial direction for all pins */
/*options :DIO_u8_INTIAL_OUTPUT
 *          DIO_u8_INTIAL_INTPUT*/

/*portA*/
#define DIO_u8_PA0_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PA1_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PA2_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PA3_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PA4_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PA5_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PA6_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PA7_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT

/*portB*/
#define DIO_u8_PB0_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB1_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB2_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB3_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB4_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB5_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB6_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PB7_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT

/*portC*/
#define DIO_u8_PC0_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC1_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC2_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC3_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC4_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC5_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC6_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT
#define DIO_u8_PC7_INTIAL_DIRECTION          DIO_u8_INTIAL_INPUT

/*portD*/
#define DIO_u8_PD0_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD1_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD2_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD3_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD4_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD5_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD6_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT
#define DIO_u8_PD7_INTIAL_DIRECTION          DIO_u8_INTIAL_OUTPUT

/*intial direction for all pins */
/*options :
DIO_OUTPUT_HIGH
DIO_OUTPUT_LOW
DIO_INPUT_FLOATING
DIO_INPUT_PULLUP */
/*portA*/
#define DIO_u8_PA0_INTIAL_VALUE          DIO_OUTPUT_HIGH
#define DIO_u8_PA1_INTIAL_VALUE          DIO_OUTPUT_HIGH
#define DIO_u8_PA2_INTIAL_VALUE          DIO_OUTPUT_HIGH
#define DIO_u8_PA3_INTIAL_VALUE          DIO_OUTPUT_HIGH
#define DIO_u8_PA4_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PA5_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PA6_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PA7_INTIAL_VALUE          DIO_INPUT_PULLUP

/*portB*/
#define DIO_u8_PB0_INTIAL_VALUE         DIO_OUTPUT_LOW
#define DIO_u8_PB1_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB2_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB3_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB4_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB5_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB6_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PB7_INTIAL_VALUE          DIO_INPUT_PULLUP

/*portC*/
#define DIO_u8_PC0_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC1_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC2_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC3_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC4_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC5_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC6_INTIAL_VALUE          DIO_INPUT_PULLUP
#define DIO_u8_PC7_INTIAL_VALUE          DIO_INPUT_PULLUP
/*PORTD*/
#define DIO_u8_PD0_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD1_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD2_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD3_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD4_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD5_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD6_INTIAL_VALUE          DIO_OUTPUT_LOW
#define DIO_u8_PD7_INTIAL_VALUE          DIO_OUTPUT_LOW

#endif
